language: java
jdk:
  - oraclejdk8 
cache:
  directories:
    - $HOME/.m2
install: 
  - ./mvnw install -N 
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw clean verify
branches:
  only:
    - master
