name: UI tests

on:
  push:
    branches: [github_action_ui_tests]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.0'
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Setup custom environment variables
        run: |
          echo "CHROME_VERSION=$(google-chrome --version | sed 's/^Google Chrome //' | cut -d. -f1)" >> $GITHUB_ENV
          echo "FIREFOX_VERSION=$(firefox --version | sed 's/Mozilla Firefox //' |  cut -d. -f1)" >> $GITHUB_ENV
      - name: Compile and Install vertx-vaadin
        run: |
          ./mvnw -B -ntp -N install && ./mvnw -B -ntp -Pcircleci -Prelease-flow,flow-ui-tests install -DskipTests -DskipVertxRun=true
      - name: Run UI tests
        run: |
          cd vertx-vaadin-flow-parent/vertx-vaadin-tests/test-root-context
          ${{github.workspace}}/mvnw -B -ntp -Pcircleci -Dvaadin.proKey=${VAADIN_PROKEY} -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver \
          -Duitest.chrome-version=${CHROME_VERSION} -Duitest.firefox-version=${FIREFOX_VERSION} \
            -Dvertx.jvmArguments="-Dorg.slf4j.simpleLogger.logFile=/tmp/verticle.log -Dvaadin.require.home.node=true -Xmx2048M -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory" \
          vaadin:clean-frontend verify
      - uses: actions/upload-artifact@v2
        if: ${{ failure() || success() }}
        with:
          name: saved-outputs
          path: |
            **/target/*-reports/*
            **/error-screenshots/*.png
            /tmp/verticle.log
            /tmp/env.test
            ~/.npm/_logs/
      
